version: '3'
services:

  queue:
    image: j3remy/testing:queue
    container_name: queue
    ports:
     - "8000:8000"

  input-manager:
    image: j3remy/testing:input-manager
    container_name: input-manager
    ports:
     - "8001:8001"
    volumes:
     - "./inputBucket/files:/files"

  output-manager:
    image: j3remy/testing:output-manager
    container_name: output-manager
    ports:
     - "8002:8002"
    volumes:
     - "./outputBucket/files:/files"

  db:
    image: j3remy/testing:db-manager
    container_name: db-manager
    ports:
     - "8003:8003"

  runner:
    image: j3remy/testing:runner
    container_name: runner
    network_mode: "host"